version: '3.1'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: master_password
      MYSQL_DATABASE: wp_learning
    volumes:
      - "./db:/var/lib/mysql"
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: master_password
      WORDPRESS_DB_NAME: wp_learning
      S3_KEY: XXX
      S3_SECRET: XXX
    volumes:
      - "./wp:/var/www/html"
  adminer: # Not required
    image: adminer
    ports:
      - 8888:8080
